import { readFile, readdir, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourceDir = join(packageRoot, 'docs')
const files = (await readdir(sourceDir)).filter((name) => /^[a-z-]+\.md$/.test(name)).sort()
const entries = await Promise.all(files.map(async (name) => [name.slice(0, -3), await readFile(join(sourceDir, name), 'utf8')]))
entries.push(['links', await readFile(resolve(packageRoot, '../../docs/api.md'), 'utf8')])
entries.sort(([left], [right]) => left.localeCompare(right))
const output = `// Generated by scripts-generate-docs.mjs from apps/api/docs/*.md and docs/api.md.\nexport const documentation: Record<string, string> = ${JSON.stringify(Object.fromEntries(entries), null, 2)}\n`
await writeFile(join(packageRoot, 'src/documentation.generated.ts'), output)
